CREATE MATERIALIZED VIEW  warzone.grading_table AS
SELECT
      m.game_category,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY damage_done) AS f_grade_damage,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY damage_done) AS d_grade_damage,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY damage_done) AS c_grade_damage,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY damage_done) AS b_grade_damage,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY damage_done) AS a_grade_damage,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY score) AS f_grade_score,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY score) AS d_grade_score,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY score) AS c_grade_score,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY score) AS b_grade_score,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY score) AS a_grade_score,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY kills) AS f_grade_kills,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY kills) AS d_grade_kills,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY kills) AS c_grade_kills,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY kills) AS b_grade_kills,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY kills) AS a_grade_kills,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY CAST(kills AS REAL) / CASE WHEN deaths = 0 THEN 1 ELSE deaths END) AS f_grade_kdr,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY CAST(kills AS REAL) / CASE WHEN deaths = 0 THEN 1 ELSE deaths END) AS d_grade_kdr,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY CAST(kills AS REAL) / CASE WHEN deaths = 0 THEN 1 ELSE deaths END) AS c_grade_kdr,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY CAST(kills AS REAL) / CASE WHEN deaths = 0 THEN 1 ELSE deaths END) AS b_grade_kdr,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY CAST(kills AS REAL) / CASE WHEN deaths = 0 THEN 1 ELSE deaths END) AS a_grade_kdr,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'trio' THEN gm.team_placement END DESC) AS a_grade_trio,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'quad' THEN gm.team_placement END DESC) AS a_grade_quad,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'duo' THEN gm.team_placement END DESC) AS a_grade_duo,
      PERCENTILE_DISC(0.9) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'solo' THEN gm.team_placement END DESC) AS a_grade_solo,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'trio' THEN gm.team_placement END DESC) AS b_grade_trio,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'quad' THEN gm.team_placement END DESC) AS b_grade_quad,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'duo' THEN gm.team_placement END DESC) AS b_grade_duo,
      PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'solo' THEN gm.team_placement END DESC) AS b_grade_solo,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'trio' THEN gm.team_placement END DESC) as c_grade_trio,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'quad' THEN gm.team_placement END DESC) AS c_grade_quad,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'duo' THEN gm.team_placement END DESC) AS c_grade_duo,
      PERCENTILE_DISC(0.50) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'solo' THEN gm.team_placement END DESC) AS c_grade_solo,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'trio' THEN gm.team_placement END DESC) AS d_grade_trio,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'quad' THEN gm.team_placement END DESC) AS d_grade_quad,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'duo' THEN gm.team_placement END DESC) AS d_grade_duo,
      PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'solo' THEN gm.team_placement END DESC) AS d_grade_solo,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'trio' THEN gm.team_placement END DESC) AS f_grade_trio,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'quad' THEN gm.team_placement END DESC) AS f_grade_quad,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'duo' THEN gm.team_placement END DESC) AS f_grade_duo,
      PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY CASE WHEN team_type = 'solo' THEN gm.team_placement END DESC) AS f_grade_solo
FROM warzone.gamer_matches gm
JOIN warzone.matches m ON m.match_id = gm.match_id
GROUP BY m.game_category