CREATE MATERIALIZED VIEW warzone.match_tier_description_values AS
SELECT
     JSON_BUILD_OBJECT(
                                                                    'category', 'average_player_kdr',
                                                                    'description', '',
                                                                    'percentiles', JSON_BUILD_OBJECT(
                                                                        'bronze_4_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.01) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .01),
                                                                        'bronze_3_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .05),
                                                                        'bronze_2_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .1),
                                                                        'bronze_1_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.15) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .15),
                                                                        'silver_4_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.2) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .2),
                                                                        'silver_3_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .25),
                                                                        'silver_2_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.3) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .3),
                                                                        'silver_1_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.35) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .35),
                                                                        'gold_4_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.4) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .4),
                                                                        'gold_3_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.45) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .45),
                                                                        'gold_2_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .5),
                                                                        'gold_1_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.55) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .55),
                                                                        'platinum_4_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.6) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .6),
                                                                        'platinum_3_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.65) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .65),
                                                                        'platinum_2_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.7) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .7),
                                                                        'platinum_1_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .75),
                                                                        'diamond_4_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.8) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .8),
                                                                        'diamond_3_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.85) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .85),
                                                                        'diamond_2_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.90) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .9),
                                                                        'diamond_1_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .95),
                                                                        'master_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.99) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .99),
                                                                        'legend_average_player_kdr', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.999) WITHIN GROUP (ORDER BY average_player_kdr), 'percentile', .999)
                                                                        )
                                                                ) as  average_player_kdr_cutoffs,


                                                                   JSON_BUILD_OBJECT(
                                                                                                                                    'category', 'average_player_score',
                                                                                                                                    'description', '',
                                                                                                                                    'percentiles', JSON_BUILD_OBJECT(
                                                                                                                                        'bronze_4_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.01) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .01),
                                                                                                                                        'bronze_3_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .05),
                                                                                                                                        'bronze_2_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .1),
                                                                                                                                        'bronze_1_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.15) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .15),
                                                                                                                                        'silver_4_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.2) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .2),
                                                                                                                                        'silver_3_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .25),
                                                                                                                                        'silver_2_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.3) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .3),
                                                                                                                                        'silver_1_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.35) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .35),
                                                                                                                                        'gold_4_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.4) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .4),
                                                                                                                                        'gold_3_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.45) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .45),
                                                                                                                                        'gold_2_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .5),
                                                                                                                                        'gold_1_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.55) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .55),
                                                                                                                                        'platinum_4_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.6) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .6),
                                                                                                                                        'platinum_3_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.65) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .65),
                                                                                                                                        'platinum_2_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.7) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .7),
                                                                                                                                        'platinum_1_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .75),
                                                                                                                                        'diamond_4_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.8) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .8),
                                                                                                                                        'diamond_3_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.85) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .85),
                                                                                                                                        'diamond_2_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.90) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .9),
                                                                                                                                        'diamond_1_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .95),
                                                                                                                                        'master_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.99) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .99),
                                                                                                                                        'legend_average_player_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.999) WITHIN GROUP (ORDER BY average_player_score), 'percentile', .999)
                                                                                                                                        )
                                                                                                                                ) as  average_player_score_cutoffs,


                                                                                                                                  JSON_BUILD_OBJECT(
                                                                                                                                                                                                                                                                    'category', 'average_player_skill_score',
                                                                                                                                                                                                                                                                    'description', '',
                                                                                                                                                                                                                                                                    'percentiles', JSON_BUILD_OBJECT(
                                                                                                                                                                                                                                                                        'bronze_4_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.01) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .01),
                                                                                                                                                                                                                                                                        'bronze_3_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.05) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .05),
                                                                                                                                                                                                                                                                        'bronze_2_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.1) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .1),
                                                                                                                                                                                                                                                                        'bronze_1_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.15) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .15),
                                                                                                                                                                                                                                                                        'silver_4_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.2) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .2),
                                                                                                                                                                                                                                                                        'silver_3_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .25),
                                                                                                                                                                                                                                                                        'silver_2_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.3) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .3),
                                                                                                                                                                                                                                                                        'silver_1_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.35) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .35),
                                                                                                                                                                                                                                                                        'gold_4_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.4) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .4),
                                                                                                                                                                                                                                                                        'gold_3_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.45) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .45),
                                                                                                                                                                                                                                                                        'gold_2_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .5),
                                                                                                                                                                                                                                                                        'gold_1_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.55) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .55),
                                                                                                                                                                                                                                                                        'platinum_4_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.6) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .6),
                                                                                                                                                                                                                                                                        'platinum_3_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.65) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .65),
                                                                                                                                                                                                                                                                        'platinum_2_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.7) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .7),
                                                                                                                                                                                                                                                                        'platinum_1_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .75),
                                                                                                                                                                                                                                                                        'diamond_4_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.8) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .8),
                                                                                                                                                                                                                                                                        'diamond_3_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.85) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .85),
                                                                                                                                                                                                                                                                        'diamond_2_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.90) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .9),
                                                                                                                                                                                                                                                                        'diamond_1_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.95) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .95),
                                                                                                                                                                                                                                                                        'master_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.99) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .99),
                                                                                                                                                                                                                                                                        'legend_average_player_skill_score', JSON_BUILD_OBJECT('value', PERCENTILE_DISC(0.999) WITHIN GROUP (ORDER BY average_player_skill_score), 'percentile', .999)
                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                ) as  average_player_skill_score_cutoffs
       
       FROM warzone.matches
       WHERE game_category = 'Warzone'