CREATE TABLE gamer_matches (
    username TEXT REFERENCES gamers(username),
    match_id TEXT REFERENCES matches(match_id),
    team TEXT,
    clan_tag TEXT,
    kills INT,
    assists INT,
    deaths INT,
    score INT,
    damage_done INT,
    damage_taken INT,
    team_placement INT,
    longest_streak INT,
    time_played INT,
    distance_traveled REAL,
    team_survival_time BIGINT,
    percent_time_moving REAL,
    wall_bangs INT,
    gulag_deaths INT,
    gulag_kills INT,
    headshots INT,
    executions INT,
    objective JSON,
    xp JSON,
    loadout JSON,
    PRIMARY KEY (username, match_id)
);