CREATE TABLE warzone.gamer_matches (
    query_username TEXT,
    query_platform TEXT,
    match_id NUMERIC(38, 0) REFERENCES warzone.matches(match_id),
    uno_id NUMERIC(38, 0),
    username TEXT,
    team TEXT,
    clan_tag TEXT,
    kills INT,
    assists INT,
    deaths INT,
    score INT,
    damage_done BIGINT,
    damage_taken BIGINT,
    team_placement INT,
    longest_streak INT,
    time_played INT,
    distance_traveled REAL,
    team_survival_time BIGINT,
    percent_time_moving REAL,
    wall_bangs INT,
    gulag_deaths INT,
    gulag_kills INT,
    headshots INT,
    executions INT,
    objective JSON,
    xp JSON,
    loadout JSON,
    contracts JSON,
    game_mode TEXT,
    game_category TEXT,
     team_type TEXT,
     start_timestamp TIMESTAMP,
     end_timestamp TIMESTAMP,
    PRIMARY KEY (uno_id, match_id)
);