create view warzone._gamer_matches_augmented(username, platform, in_game_username, team, clan_tag, kills, assists, deaths, damage_taken, time_played, score, damage_done, team_placement, longest_streak, distance_traveled, team_survival_time, percent_time_moving, wall_bangs, gulag_deaths, gulag_kills, headshots, executions, objective, xp, match_id, start_time, end_time, map, mode, duration, version, game_type, player_count, team_count, start_timestamp, end_timestamp, team_type, is_warzone_match) as
SELECT gm.query_username as username,
       gm.query_platform as platform,
       gm.username as in_game_username,
       gm.team,
       gm.clan_tag,
       gm.kills,
       gm.assists,
       gm.deaths,
       gm.damage_taken,
       gm.time_played,
       gm.score,
       gm.damage_done,
       gm.team_placement,
       gm.longest_streak,
       gm.distance_traveled,
       gm.team_survival_time,
       gm.percent_time_moving,
       gm.wall_bangs,
       gm.gulag_deaths,
       gm.gulag_kills,
       gm.headshots,
       gm.executions,
       gm.objective,
       gm.xp,
       m.match_id,
       m.start_time,
       m.end_time,
       m.map,
       m.mode,
       m.duration,
       m.version,
       m.game_type,
       m.player_count,
       m.team_count,
       m.start_timestamp,
       m.end_timestamp,
       m.team_type,
       m.is_warzone_match
FROM warzone.gamer_matches_augmented gm
         JOIN warzone.matches_augmented m ON gm.match_id = m.match_id;

alter table warzone._gamer_matches_augmented owner to fjcexshgdfbtia;

